name: tayt_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.6.4
  provider: ^6.0.2
  font_awesome_flutter: ^10.6.0
  toggle_switch: ^1.4.0
  animate_gradient: ^0.0.2+1
  image_picker: ^1.0.4
  get: ^4.6.6
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.9
  easy_search_bar: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/

  fonts:
    - family: "DM Sans"
      fonts:
        - asset: "assets/fonts/DMSans-Black.ttf"
          style: "normal"
          weight: 900
        - asset: "assets/fonts/DMSans-Bold.ttf"
          style: "normal"
          weight: 700
        - asset: "assets/fonts/DMSans-ExtraBold.ttf"
          style: "normal"
          weight: 800
        - asset: "assets/fonts/DMSans-ExtraLight.ttf"
          style: "normal"
          weight: 200
        - asset: "assets/fonts/DMSans-Light.ttf"
          style: "normal"
          weight: 300
        - asset: "assets/fonts/DMSans-Medium.ttf"
          style: "normal"
          weight: 500
        - asset: "assets/fonts/DMSans-Regular.ttf"
          style: "normal"
          weight: 400
        - asset: "assets/fonts/DMSans-SemiBold.ttf"
          style: "italic"
          weight: 600
    - family: "Poppins"
      fonts:
        - asset: "assets/fonts/Poppins-Thin.ttf"
          style: "normal"
          weight: 100
        - asset: "assets/fonts/Poppins-ExtraLight.ttf"
          style: "normal"
          weight: 200
        - asset: "assets/fonts/Poppins-Light.ttf"
          style: "normal"
          weight: 300
        - asset: "assets/fonts/Poppins-700.ttf"
          style: "normal"
          weight: 700
        - asset: "assets/fonts/Poppins-Regular.ttf"
          style: "normal"
          weight: 400
        - asset: "assets/fonts/Poppins-Medium.ttf"
          style: "normal"
          weight: 500
        - asset: "assets/fonts/Poppins-SemiBold.ttf"
          style: "normal"
          weight: 600
    - family: "GT Haptik"
      fonts:
        - asset: assets/fonts/GTHaptik-Regular.ttf
          style: normal
    - family: "Inter"
      fonts:
        - asset: "assets/fonts/Inter-Bold.ttf"
          style: "normal"
          weight: 700
        - asset: "assets/fonts/Inter-ExtraBold.ttf"
          style: "normal"
          weight: 800
        - asset: "assets/fonts/Inter-Regular.ttf"
          style: "normal"
          weight: 400
        - asset: "assets/fonts/Inter-Medium.ttf"
          style: "normal"
          weight: 500
        - asset: "assets/fonts/Inter-SemiBold.ttf"
          style: "normal"
          weight: 600
    - family: "Helvetica Neue"
      fonts:
        - asset: "assets/fonts/HelveticaNeueMedium.otf"
          style: "normal"
          weight: 400
        - asset: "assets/fonts/HelveticaNeueBold.otf"
          style: "normal"
          weight: 700
        - asset: "assets/fonts/HelveticaNeueLight.otf"
          style: "normal"
          weight: 300
        - asset: "assets/fonts/HelveticaNeueThin.otf"
          style: "normal"
          weight: 100